language: python
python:
  - "3.5"
install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls
script:
  - python3 manage.py test gearspotting
  - coverage run --source=gearspotting manage.py test gearspotting
after_success: coveralls
