# Generated by Django 5.1.13 on 2025-10-19 18:01

import django.db.migrations.operations.special
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('gear', '0001_initial'), ('gear', '0002_auto_20170928_1353'), ('gear', '0003_gear_description_html'), ('gear', '0004_auto_20230207_1022'), ('gear', '0005_geartag'), ('gear', '0006_auto_20251019_1035')]

    initial = True

    dependencies = [
        ('manufacturer', '0001_initial'),
        ('photo', '0001_initial'),
        ('tag', '0002_auto_20251019_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('slug', models.SlugField(editable=False, max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturer.manufacturer')),
                ('description_html', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['manufacturer__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GearPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear.gear')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.photo')),
            ],
        ),
        migrations.CreateModel(
            name='GearTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear.gear')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.tag')),
            ],
        ),
    ]
