# Generated by Django 3.2.16 on 2023-02-07 10:22

import markdown
from django.db import migrations


def forwards(apps, schema_editor):
    Gear = apps.get_model('gear', 'Gear')
    for gear in Gear.objects.all():
        gear.description_html = markdown.markdown(gear.description)
        gear.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0003_gear_description_html'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
