# Generated by Django 5.1.13 on 2025-10-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=256)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
