# Generated by Django 2.0.3 on 2018-03-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20170928_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyProfile',
        ),
    ]
