# Generated by Django 5.1.13 on 2025-10-19 18:06

import django.db.migrations.operations.special
import django.db.models.deletion
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# gearspotting.musician.migrations.0004_auto_20230207_1100
# gearspotting.musician.migrations.0006_auto_20251019_1035

class Migration(migrations.Migration):

    replaces = [('musician', '0001_initial'), ('musician', '0002_auto_20170928_1353'), ('musician', '0003_musician_description_html'), ('musician', '0004_auto_20230207_1100'), ('musician', '0005_musiciantag'), ('musician', '0006_auto_20251019_1035'), ('musician', '0007_remove_musician_tags')]

    initial = True

    dependencies = [
        ('photo', '0001_initial'),
        ('tag', '0002_auto_20251019_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description_html', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MusicianPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.musician')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.photo')),
            ],
        ),
        migrations.CreateModel(
            name='MusicianTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.musician')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.tag')),
            ],
        ),
    ]
