# Generated by Django 3.2.16 on 2023-02-07 11:00

import markdown
from django.db import migrations


def forwards(apps, schema_editor):
    M = apps.get_model('musician', 'Musician')
    for m in M.objects.all():
        m.description_html = markdown.markdown(m.description)
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0003_musician_description_html'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
