# Generated by Django 5.1.13 on 2025-10-19 14:35

from django.db import migrations

def update_all_contenttypes():
    from django.apps import apps
    from django.contrib.contenttypes.management import create_contenttypes

    for app_config in apps.get_app_configs():
        create_contenttypes(app_config)

def taggit_tags(apps, schema_editor):
    update_all_contenttypes()
    Musician = apps.get_model("musician", "Musician")
    ContentType = apps.get_model("contenttypes", "ContentType")
    ct = ContentType.objects.get(app_label="musician", model="musician")
    MusicianTag = apps.get_model("musician", "MusicianTag")
    TaggedItem = apps.get_model("taggit", "TaggedItem")
    Tag = apps.get_model("tag", "Tag")
    for m in Musician.objects.all():
        for t in TaggedItem.objects.filter(object_id=m.id, content_type_id=ct.id):
            tag = Tag.objects.get(name=t.tag.name)
            MusicianTag.objects.create(musician=m, tag=tag)


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0005_musiciantag'),
    ]

    operations = [
        migrations.RunPython(taggit_tags, reverse_code=migrations.RunPython.noop)
    ]
