# Generated by Django 5.1.13 on 2025-10-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0006_auto_20251019_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='tags',
        ),
    ]
