# Generated by Django 3.2.16 on 2023-02-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_auto_20170928_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
