# Generated by Django 3.2.16 on 2023-02-07 11:04
import markdown
from django.db import migrations


def forwards(apps, schema_editor):
    M = apps.get_model('photo', 'Photo')
    for m in M.objects.all():
        m.caption_html = markdown.markdown(m.caption)
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_photo_caption_html'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
