on: push
name: run tests
jobs:
  buildDockerImage:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build docker image
      uses: actions/docker/cli@master
      run: docker build -t thraxil/gearspotting:${{ github.sha }} .
